baseURL = "https://nicktify.com"
languageCode = "en-us"
title = "Nicolás Aguilar - nicktify"
theme="archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "nicktify"

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	# subtitle = "Full Stack Developer - Data Engineer - AI Engineer student"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nicktify"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nicktify"

## email
[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:contact@nicktify.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

# [deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

URL = "s3://nicktify-blog-v2?region=us-west-2"

